### ISSUE TITLE
Connection failed due to lack of TLS 1.2 support

### ISSUE THREAD

**Issue by tsuchm** [LLK/scratch-link#184] opened 2020-08-18 01:54 UTC
### Actual Behavior

Because modern web browser such as Google Chrome and Edge rejects connections using either TLS/1.0 or TLS/1.1, I failed to connect Scratch to LEGO WeDo 2.0.

### Steps to Reproduce

Connect https://device-manager.scratch.mit.edu:20110/ and see the error message produced by the browser.

### Method to Defuse This Issue

It is possible to allow security exception to connect https://device-manager.scratch.mit.edu:20110/.

**Comment by apple502j** [comment] 2020-08-18 04:58
Should be fixed in the latest version.

**Comment by cwillisf** [comment] 2020-08-18 17:55
This seems to be a duplicate of #179 -- please update to version 1.3.66 and see if that resolves the problem. Thanks!

**Closed as completed** 2020-08-18 18:16 UTC

**Comment by tsuchm** [comment] 2020-08-18 23:24
Thanks for your comment.

However, it arrises another problem.  Although I have installed the latest version of Scratch Link from Microsoft App Store at Aug 19, its version is still 1.3.57.0.  Could you update the registration of Microsoft App Store?
