### ISSUE TITLE
CERT REVOKED

### ISSUE THREAD

**Issue by wwj718** [LLK/scratch-link#177] opened 2020-07-05 05:57 UTC
### Expected Behavior

work with wedo2

### Actual Behavior

![image](https://user-images.githubusercontent.com/3153878/86526501-4befd680-bec7-11ea-8bd7-a80996367a8c.png)

![image](https://user-images.githubusercontent.com/3153878/86526513-6de95900-bec7-11ea-8e11-f02ab9b648b7.png)

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

### Operating System and Browser

Mac OS 10.13

Scratch link 1.3.0

**Comment by apple502j** [comment] 2020-07-05 06:02
Duplicate of #175 (which is fixed, waiting for the release)

**Closed as completed** 2020-07-05 10:57 UTC
